# Generated by Django 3.0.7 on 2020-08-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('nickname', models.CharField(max_length=32)),
                ('account', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('passward', models.CharField(max_length=32)),
            ],
        ),
    ]
