# Generated by Django 3.0.7 on 2020-08-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passward',
            new_name='password',
        ),
    ]
