# Generated by Django 3.0.7 on 2020-08-24 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200823_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='account',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='account',
            new_name='user',
        ),
    ]
