# Generated by Django 3.0.7 on 2020-08-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200824_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='content',
            field=models.CharField(default=' ', max_length=512),
        ),
        migrations.AddField(
            model_name='favorite',
            name='link',
            field=models.CharField(default=' ', max_length=512),
        ),
        migrations.AddField(
            model_name='favorite',
            name='pubDate',
            field=models.CharField(default=' ', max_length=16),
        ),
        migrations.AddField(
            model_name='favorite',
            name='scource',
            field=models.CharField(default=' ', max_length=16),
        ),
        migrations.AddField(
            model_name='favorite',
            name='title',
            field=models.CharField(default=' ', max_length=32),
        ),
    ]
