# Generated by Django 3.0.7 on 2020-08-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200824_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='havePic',
            field=models.BooleanField(default=False),
        ),
    ]
