# Generated by Django 3.0.7 on 2020-08-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_favorite_havepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='imageurls',
            field=models.CharField(default=' ', max_length=512),
        ),
    ]
