# Generated by Django 3.0.7 on 2020-08-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_favorite_imageurls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='scource',
            new_name='source',
        ),
    ]
